services:
  mysql:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example_root_password
      - MYSQL_DATABASE=example_db
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=example_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=example_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
