services:
  database:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=example_db
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql/data

  cache:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
