services:
  backend:
    build: ./backend
    environment:
      MESSAGE: "Hello from Docker Compose"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  gateway:
    build: ./gateway
    environment:
      - BACKEND_URL=http://backend:8080
      - MESSAGE="xxx"
    ports:
      - "8081:8081"
    depends_on:
      - backend

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD="test"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data: